### ISSUE TITLE
CUDA Out of memory on 8 GiB GPU when trying to convert model

### ISSUE THREAD

**Issue by ginto-sakata** [ddPn08/Radiata#35]
I tried several different models but i'm getting the same CUDA out of memory error:

lsmith-lsmith-1  | torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 512.00 MiB (GPU 0; 8.00 GiB total capacity; 6.98 GiB already allocated; 0 bytes free; 7.20 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Running in Docker on Windows, RTX 3050

**Comment by fkunn1326** [comment]
Might work with float16, static batch and preview features enabled.

**Comment by Stax124** [comment]
@ginto-sakata can you please tell me what model did you try to convert?

I also have a 3050 and this issue seems to come from an error in the onnx conversion process - the model isn't properly cast down to float16 and takes much more VRAM than necessary -> going OOM on some GPUs, ours included.

The theoretical fix is to just cast the model to float16 before converting it. This might be fixed in the future by doing this process automatically. If I find the exact function causing this then there is a possibility of fixing this bug.

This conversion process can be done in A111 - [relevant link](https://www.reddit.com/r/StableDiffusion/comments/zcbcr8/comment/iyyc7c2/?utm_source=share&utm_medium=web2x&context=3)

Good luck

**Comment by KNARZ0R** [comment]
Hi,
at first thank you for your efforts to make the process faster!

I am having the same problem with my 3060 12GB. I was trying to convert https://huggingface.co/SG161222/Realistic_Vision_V1.3

```
lsmith-lsmith-1  | The config attributes {'class_embed_type': None, 'dual_cross_attention': False, 'mid_block_type': 'UNetMidBlock2DCrossAttn', 'num_class_embeds': None, 'only_cross_attention': False, 'resnet_time_scale_shift': 'default', 'upcast_attention': False, 'use_linear_projection': False} were passed to UNet2DConditionModel, but are not expected and will be ignored. Please verify your config.json configuration file.
lsmith-lsmith-1  | /app/./submodules/diffusers_0_7_2/src/diffusers/models/unet_2d_condition.py:273: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
lsmith-lsmith-1  |   if any(s % default_overall_up_factor != 0 for s in sample.shape[-2:]):
lsmith-lsmith-1  | /opt/conda/lib/python3.10/site-packages/torch/nn/functional.py:2515: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
lsmith-lsmith-1  |   _verify_batch_size([input.size(0) * input.size(1) // num_groups, num_groups] + list(input.size()[2:]))
lsmith-lsmith-1  | /app/./submodules/diffusers_0_7_2/src/diffusers/models/attention.py:465: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
lsmith-lsmith-1  |   tensor = tensor.reshape(batch_size, seq_len, head_size, dim // head_size)
lsmith-lsmith-1  | /app/./submodules/diffusers_0_7_2/src/diffusers/models/attention.py:466: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
lsmith-lsmith-1  |   tensor = tensor.permute(0, 2, 1, 3).reshape(batch_size * head_size, seq_len, dim // head_size)
lsmith-lsmith-1  | /app/./submodules/diffusers_0_7_2/src/diffusers/models/attention.py:472: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
lsmith-lsmith-1  |   tensor = tensor.reshape(batch_size // head_size, head_size, seq_len, dim)
lsmith-lsmith-1  | /app/./submodules/diffusers_0_7_2/src/diffusers/models/attention.py:473: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
lsmith-lsmith-1  |   tensor = tensor.permute(0, 2, 1, 3).reshape(batch_size // head_size, seq_len, dim * head_size)
lsmith-lsmith-1  | /app/./submodules/diffusers_0_7_2/src/diffusers/models/resnet.py:111: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
lsmith-lsmith-1  |   assert hidden_states.shape[1] == self.channels
lsmith-lsmith-1  | /app/./submodules/diffusers_0_7_2/src/diffusers/models/resnet.py:116: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
lsmith-lsmith-1  |   assert hidden_states.shape[1] == self.channels
lsmith-lsmith-1  | /app/./submodules/diffusers_0_7_2/src/diffusers/models/resnet.py:39: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
lsmith-lsmith-1  |   assert hidden_states.shape[1] == self.channels
lsmith-lsmith-1  | /app/./submodules/diffusers_0_7_2/src/diffusers/models/resnet.py:52: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
lsmith-lsmith-1  |   if hidden_states.shape[0] >= 64:
lsmith-lsmith-1  | ERROR:    Exception in ASGI application
lsmith-lsmith-1  | Traceback (most recent call last):
lsmith-lsmith-1  |   File "/opt/conda/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
lsmith-lsmith-1  |     result = await app(  # type: ignore[func-returns-value]
lsmith-lsmith-1  |   File "/opt/conda/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
lsmith-lsmith-1  |     return await self.app(scope, receive, send)
lsmith-lsmith-1  |   File "/opt/conda/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
lsmith-lsmith-1  |     await super().__call__(scope, receive, send)
lsmith-lsmith-1  |   File "/opt/conda/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
lsmith-lsmith-1  |     await self.middleware_stack(scope, receive, send)
lsmith-lsmith-1  |   File "/opt/conda/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
lsmith-lsmith-1  |     raise exc
lsmith-lsmith-1  |   File "/opt/conda/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
lsmith-lsmith-1  |     await self.app(scope, receive, _send)
lsmith-lsmith-1  |   File "/opt/conda/lib/python3.10/site-packages/starlette/middleware/cors.py", line 92, in __call__
lsmith-lsmith-1  |     await self.simple_response(scope, receive, send, request_headers=headers)
lsmith-lsmith-1  |   File "/opt/conda/lib/python3.10/site-packages/starlette/middleware/cors.py", line 147, in simple_response
lsmith-lsmith-1  |     await self.app(scope, receive, send)
lsmith-lsmith-1  |   File "/opt/conda/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
lsmith-lsmith-1  |     raise exc
lsmith-lsmith-1  |   File "/opt/conda/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
lsmith-lsmith-1  |     await self.app(scope, receive, sender)
lsmith-lsmith-1  |   File "/opt/conda/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
lsmith-lsmith-1  |     raise e
lsmith-lsmith-1  |   File "/opt/conda/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
lsmith-lsmith-1  |     await self.app(scope, receive, send)
lsmith-lsmith-1  |   File "/opt/conda/lib/python3.10/site-packages/starlette/routing.py", line 706, in __call__
lsmith-lsmith-1  |     await route.handle(scope, receive, send)
lsmith-lsmith-1  |   File "/opt/conda/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
lsmith-lsmith-1  |     await self.app(scope, receive, send)
lsmith-lsmith-1  |   File "/opt/conda/lib/python3.10/site-packages/starlette/routing.py", line 69, in app
lsmith-lsmith-1  |     await response(scope, receive, send)
lsmith-lsmith-1  |   File "/opt/conda/lib/python3.10/site-packages/starlette/responses.py", line 266, in __call__
lsmith-lsmith-1  |     async with anyio.create_task_group() as task_group:
lsmith-lsmith-1  |   File "/opt/conda/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 662, in __aexit__
lsmith-lsmith-1  |     raise exceptions[0]
lsmith-lsmith-1  |   File "/opt/conda/lib/python3.10/site-packages/starlette/responses.py", line 269, in wrap
lsmith-lsmith-1  |     await func()
lsmith-lsmith-1  |   File "/opt/conda/lib/python3.10/site-packages/starlette/responses.py", line 258, in stream_response
lsmith-lsmith-1  |     async for chunk in self.body_iterator:
lsmith-lsmith-1  |   File "/opt/conda/lib/python3.10/site-packages/starlette/concurrency.py", line 63, in iterate_in_threadpool
lsmith-lsmith-1  |     yield await anyio.to_thread.run_sync(_next, iterator)
lsmith-lsmith-1  |   File "/opt/conda/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
lsmith-lsmith-1  |     return await get_asynclib().run_sync_in_worker_thread(
lsmith-lsmith-1  |   File "/opt/conda/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
lsmith-lsmith-1  |     return await future
lsmith-lsmith-1  |   File "/opt/conda/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
lsmith-lsmith-1  |     result = context.run(func, *args)
lsmith-lsmith-1  |   File "/opt/conda/lib/python3.10/site-packages/starlette/concurrency.py", line 53, in _next
lsmith-lsmith-1  |     return next(iterator)
lsmith-lsmith-1  |   File "/app/./modules/http/routes/engine_api.py", line 49, in generator
lsmith-lsmith-1  |     raise e
lsmith-lsmith-1  |   File "/app/./modules/http/routes/engine_api.py", line 45, in generator
lsmith-lsmith-1  |     for data in builder.build(generator=True, on_end=lambda: runners.set_default_model()):
lsmith-lsmith-1  |   File "/app/./modules/diffusion/tensorrt/engine.py", line 123, in build
lsmith-lsmith-1  |     engine = build_engine(
lsmith-lsmith-1  |   File "/app/./modules/diffusion/tensorrt/engine.py", line 41, in build_engine
lsmith-lsmith-1  |     torch.onnx.export(
lsmith-lsmith-1  |   File "/opt/conda/lib/python3.10/site-packages/torch/onnx/__init__.py", line 350, in export
lsmith-lsmith-1  |     return utils.export(
lsmith-lsmith-1  |   File "/opt/conda/lib/python3.10/site-packages/torch/onnx/utils.py", line 163, in export
lsmith-lsmith-1  |     _export(
lsmith-lsmith-1  |   File "/opt/conda/lib/python3.10/site-packages/torch/onnx/utils.py", line 1074, in _export
lsmith-lsmith-1  |     graph, params_dict, torch_out = _model_to_graph(
lsmith-lsmith-1  |   File "/opt/conda/lib/python3.10/site-packages/torch/onnx/utils.py", line 727, in _model_to_graph
lsmith-lsmith-1  |     graph, params, torch_out, module = _create_jit_graph(model, args)
lsmith-lsmith-1  |   File "/opt/conda/lib/python3.10/site-packages/torch/onnx/utils.py", line 602, in _create_jit_graph
lsmith-lsmith-1  |     graph, torch_out = _trace_and_get_graph_from_model(model, args)
lsmith-lsmith-1  |   File "/opt/conda/lib/python3.10/site-packages/torch/onnx/utils.py", line 517, in _trace_and_get_graph_from_model
lsmith-lsmith-1  |     trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
lsmith-lsmith-1  |   File "/opt/conda/lib/python3.10/site-packages/torch/jit/_trace.py", line 1175, in _get_trace_graph
lsmith-lsmith-1  |     outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
lsmith-lsmith-1  |   File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
lsmith-lsmith-1  |     return forward_call(*input, **kwargs)
lsmith-lsmith-1  |   File "/opt/conda/lib/python3.10/site-packages/torch/jit/_trace.py", line 127, in forward
lsmith-lsmith-1  |     graph, out = torch._C._create_graph_by_tracing(
lsmith-lsmith-1  |   File "/opt/conda/lib/python3.10/site-packages/torch/jit/_trace.py", line 118, in wrapper
lsmith-lsmith-1  |     outs.append(self.inner(*trace_inputs))
lsmith-lsmith-1  |   File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
lsmith-lsmith-1  |     return forward_call(*input, **kwargs)
lsmith-lsmith-1  |   File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1118, in _slow_forward
lsmith-lsmith-1  |     result = self.forward(*input, **kwargs)
lsmith-lsmith-1  |   File "/app/./submodules/diffusers_0_7_2/src/diffusers/models/unet_2d_condition.py", line 333, in forward
lsmith-lsmith-1  |     sample = upsample_block(
lsmith-lsmith-1  |   File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
lsmith-lsmith-1  |     return forward_call(*input, **kwargs)
lsmith-lsmith-1  |   File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1118, in _slow_forward
lsmith-lsmith-1  |     result = self.forward(*input, **kwargs)
lsmith-lsmith-1  |   File "/app/./submodules/diffusers_0_7_2/src/diffusers/models/unet_2d_blocks.py", line 1190, in forward
lsmith-lsmith-1  |     hidden_states = attn(hidden_states, encoder_hidden_states=encoder_hidden_states).sample
lsmith-lsmith-1  |   File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
lsmith-lsmith-1  |     return forward_call(*input, **kwargs)
lsmith-lsmith-1  |   File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1118, in _slow_forward
lsmith-lsmith-1  |     result = self.forward(*input, **kwargs)
lsmith-lsmith-1  |   File "/app/./submodules/diffusers_0_7_2/src/diffusers/models/attention.py", line 202, in forward
lsmith-lsmith-1  |     hidden_states = block(hidden_states, context=encoder_hidden_states, timestep=timestep)
lsmith-lsmith-1  |   File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
lsmith-lsmith-1  |     return forward_call(*input, **kwargs)
lsmith-lsmith-1  |   File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1118, in _slow_forward
lsmith-lsmith-1  |     result = self.forward(*input, **kwargs)
lsmith-lsmith-1  |   File "/app/./submodules/diffusers_0_7_2/src/diffusers/models/attention.py", line 404, in forward
lsmith-lsmith-1  |     hidden_states = self.attn1(norm_hidden_states) + hidden_states
lsmith-lsmith-1  |   File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
lsmith-lsmith-1  |     return forward_call(*input, **kwargs)
lsmith-lsmith-1  |   File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1118, in _slow_forward
lsmith-lsmith-1  |     result = self.forward(*input, **kwargs)
lsmith-lsmith-1  |   File "/app/./submodules/diffusers_0_7_2/src/diffusers/models/attention.py", line 497, in forward
lsmith-lsmith-1  |     hidden_states = self._attention(query, key, value)
lsmith-lsmith-1  |   File "/app/./submodules/diffusers_0_7_2/src/diffusers/models/attention.py", line 514, in _attention
lsmith-lsmith-1  |     attention_probs = attention_scores.softmax(dim=-1)
lsmith-lsmith-1  | RuntimeError: CUDA out of memory. Tried to allocate 1024.00 MiB (GPU 0; 11.76 GiB total capacity; 8.60 GiB already allocated; 300.12 MiB free; 10.26 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

I tried to solve it with `export PYTORCH_CUDA_ALLOC_CONF="garbage_collection_threshold:0.6,max_split_size_mb:256"` on top of the `launch.sh` but it does not help.

I even tried to convert the original model to fp16 only with pruning (using automatic1111) but I can not manage to place my conversion in the correct file path.

**Comment by JannyPvP** [comment]
Got a 3050 too and I'm not even able to convert any model. I even tried a local one with FP16, Static Batch, Preview Features and launch arguments.
![image](https://user-images.githubusercontent.com/125215990/224702472-22376fc4-85f5-41de-928b-004b79aa015b.png)

**Comment by Stax124** [comment]
@JannyPvP It should be possible to convert it on 8GB GPUs if you have: Static batch, Float16, Preview features, and disabled dynamic size.
Try closing all other apps that might suck up VRAM.

If it still doesn't work, you can try [VoltaML](https://voltaml.github.io/voltaML-fast-stable-diffusion/installation/docker.html), I switched it AITemplate instead, so it can be compiled even on 6GB cards - tho with a performance hit compared to TensorRT (I get about 9-10it/s 512x512 on my RTX 3050, TRT was about 12.5it/s)

@KNARZ0R from the commits that I have seen, @ddPn08 patched that fp16 revision bug a few days ago, you can give it a try if you want.

I am quite busy with Volta, but if I get some time, I will try to look at those bugs.

**Comment by ddPn08** [comment]
Closing this issue as the project has been significantly updated. Please reopen if you still have problems.
