### ISSUE TITLE
What is the cause of this ERROR?

### ISSUE THREAD

**Issue by SERO3452** [ddPn08/Radiata#71]
Installing requirements
Installing tensorrt requirements
Traceback (most recent call last):
  File "G:\Radiata\launch.py", line 224, in <module>
    prepare_environment()
  File "G:\Radiata\launch.py", line 206, in prepare_environment
    install_tensorrt()
  File "G:\Radiata\launch.py", line 133, in install_tensorrt
    assert (
AssertionError: Could not find TensorRT. Please check if it is installed correctly.

**Comment by ddPn08** [comment]
To use TensorRT mode, TensorRT must be installed on your computer.
https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html

**Comment by SERO3452** [comment]
Thank you very much! I was able to solve the problem!

**Comment by boricuapab** [comment]
@SERO3452 could you give steps as to how you fixed it.

I'm getting the error as well through a conda env.

I also made the system environment variables.

![tensorRTIssue](https://github.com/ddPn08/Radiata/assets/61924816/e43dd0c1-3b7c-46dd-a93c-9094fcbc0900)

![cudatoolkit12EnvSet](https://github.com/ddPn08/Radiata/assets/61924816/d838e6d4-c8e4-4c40-b801-b0ec5903383a)

![tensorRTIssueEnvSet](https://github.com/ddPn08/Radiata/assets/61924816/552dbda1-2620-40db-b826-e5c17c92f8dc)
