### ISSUE TITLE
Deepfloyd bug

### ISSUE THREAD

**Issue by zbw66** [ddPn08/Radiata#98]
### Describe the bug

click stage1 button and i recieve the repo as follows:

Python 3.10.5 (main, Jun 19 2023, 14:06:52) [GCC 9.4.0]
Commit hash: 4b19badffb5f76efb83275c0b6f9f31742408cde
Installing requirements
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
[INFO] HTTP Request: POST http://localhost:7860/api/predict "HTTP/1.1 200 OK"
Downloading shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 3871.07it/s]
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.15s/it]
Traceback (most recent call last):
  File "/Radiata/venv/lib/python3.10/site-packages/gradio/routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "/Radiata/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "/Radiata/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/Radiata/venv/lib/python3.10/site-packages/gradio/utils.py", line 336, in async_iteration
    return await iterator.__anext__()
  File "/Radiata/venv/lib/python3.10/site-packages/gradio/utils.py", line 329, in __anext__
    return await anyio.to_thread.run_sync(
  File "/Radiata/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Radiata/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/Radiata/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/Radiata/venv/lib/python3.10/site-packages/gradio/utils.py", line 312, in run_sync_iterator_async
    return next(iterator)
  File "/Radiata/modules/tabs/deepfloyd_if.py", line 61, in generate_image
    for data in fn(
  File "/Radiata/modules/diffusion/pipelines/deepfloyd_if.py", line 193, in stage_I
    prompt_embeds, negative_prompt_embeds = self._encode_prompt(
  File "/Radiata/modules/diffusion/pipelines/deepfloyd_if.py", line 166, in _encode_prompt
    self.load_pipeline("I", "t5")
  File "/Radiata/modules/diffusion/pipelines/deepfloyd_if.py", line 121, in load_pipeline
    ).to(self.device[0])
  File "/Radiata/venv/lib/python3.10/site-packages/transformers/modeling_utils.py", line 1896, in to
    return super().to(*args, **kwargs)
  File "/Radiata/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
  File "/Radiata/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/Radiata/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/Radiata/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 4 more times]
  File "/Radiata/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/Radiata/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
NotImplementedError: Cannot copy out of meta tensor; no data!

### Reproduction

rewrite user-env.sh:
export COMMANDLINE_ARGS="--deepfloyd_if"
rewrite launch.sh(guess forgot to change "if [[ -f webui-user.sh ]]" to "if [[ -f user-env.sh ]]" in origin code of lauch.sh)
run  bash launch.sh

### Expected behavior

hope stage1-3 to work healthily

### System Info

python=3.10
ubuntu20.04
torch=2.0.0+cu118
cuda=11.8
cudnn=8
tensorrt=8.6.1

### Validations

- [X] Read the [docs](https://ddPn08.github.io/Radiata/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by ddPn08** [comment]
Sorry for leaving it for a while. Sorry, I gave up on the Deepfloyd IF implementation. We are moving towards SDXL support instead.

**Comment by zbw66** [comment]
Tks for your reply,
deepfloyd launch successfully,many issus  are related to vram,when i use A100, troubles are disappeared

SDXL already open source??？looking forward to your work haha,
AND i wanna know about text_encoder: The difference between
T5EncoderModel.from_pretrained( "DeepFloyd/IF-I-XL-v1.0")  and google/t5-v1_1-xxl  ????? are they the same???

**Comment by ddPn08** [comment]
Yes I think they are probably the same.

**Comment by zbw66** [comment]
bingo!!  looking forword to SDXL
